server:
  port: 8081

spring:
  application:
    name: eolma-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: public
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  kafka:
    producer:
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 3

jwt:
  access-token-expiration: 1800000   # 30min
  refresh-token-expiration: 604800000 # 7days
